# Generated by Django 2.0 on 2017-12-26 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveceria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerveceria', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cerverza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerveza', models.CharField(max_length=10)),
                ('categoria', models.CharField(choices=[('AR', 'Artesanal'), ('IN', 'Industrial')], default=[('', '---------')], max_length=2)),
                ('existencia', models.IntegerField(default=0)),
                ('board', models.BooleanField(default=False)),
                ('cerveceria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TabernaApp.Cerveceria')),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Cerveza',
                'verbose_name_plural': 'Tipos de Cervezas',
            },
        ),
        migrations.AddField(
            model_name='cerverza',
            name='presentaciones',
            field=models.ManyToManyField(to='TabernaApp.Presentacion'),
        ),
        migrations.AddField(
            model_name='cerverza',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TabernaApp.TipoCerveza'),
        ),
    ]
